server:
  port: 8080
  servlet:
    context-path: /identity  # Giữ nguyên nếu bạn dùng

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/viblo_demo_db"
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Tự động cập nhật bảng
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:  # OAuth2 cho Google (Gmail)
            client-id: your-google-client-id
            client-secret: your-google-client-secret
            scope: email, profile
            redirect-uri: http://localhost:8080/identity/login/oauth2/code/google
          facebook:  # OAuth2 cho Facebook
            client-id: your-fb-client-id
            client-secret: your-fb-client-secret
            scope: email, public_profile
            redirect-uri: http://localhost:8080/identity/login/oauth2/code/facebook